openapi: "3.0.0"
info:
  version: 0.0.0
  title: portal
  description: UCL ARC portal web API
servers:
  - url: /api/v0

paths:
  /me:
    get:
      description: Me endpoint
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MeResponse"
        default:
          description: Unexpected error

components:
  schemas:
    MeResponse:
      type: object
      required:
        - username
        - roles
      properties:
        username:
          type: string
        roles:
          type: array
          items:
            type: string
