services:
  test:
    # This is just a stub - cypress intended
    image: curlimages/curl:8.12.1
    command: ["curl", "--fail", "--connect-timeout", "10", "http://nginx/"]
    depends_on:
      - nginx

  web-api:
    build:
      context: ..
      target: web-api-release
    environment:
      PORT: "8080"
      IS_TESTING: true
      DATABASE_DSN: host=postgres user=postgres password=postgres dbname=dev sslmode=disable TimeZone=UTC # pragma: allowlist secret
    depends_on:
      - postgres

  web-frontend:
    build:
      context: ..
      target: web-frontend-release
    environment:
      PORT: "8080"
      IS_TESTING: true

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
      - web-frontend

  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: postgres # pragma: allowlist secret
      POSTGRES_DB: dev

  cypress:
    image: cypress/included:13.5.0 # or latest known-good version
    depends_on:
      - nginx
    working_dir: /web
    volumes:
      - ../web:/web
    environment:
      - CYPRESS_baseUrl=http://nginx:80
      - CYPRESS_VIDEO=false
    command: ["npx", "cypress", "run", "--config-file", "cypress.config.cjs"]
