---
name: Test
on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run unit tests
        run: make test-unit

  e2e:
    runs-on: ubuntu-latest

    needs: [unit]

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('web/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install frontend dependencies
        run: cd web && npm ci

      - name: Run e2e tests
        run: make test-e2e-release
        working-directory: ${{ github.workspace }}

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots/

      - name: Upload Cypress videos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: web/cypress/videos/
